INSERT INTO ksiazki (tytul, autor, cena,id_wydawnictwa)
VALUES ('Dunkel','Jakub Bielawski' ,39.99,1 ),
 ('Chodź ze mną','Konrad Możdżeń' ,49.99,1 ),
 ('W górach szaleństwa','H.P. Lovecraft' ,19.99,1 ),
 ('Zgroza w Dunwitch','H.P. Lovecraft' ,39.99,1 ),
 ('Przyszła na Sarnath zagłada','H.P. Lovecraft' ,39.99,1 ),
 ('Zew Cthulhu','H.P. Lovecraft',19.99,1 ),
 ('Państwo','Platon',39.99,2 ),
 ('Rozmyślania','Marek Aureliusz',19.99,2 ),
 ('Wiedźmin: Sezon Burz','Andrzej Sapkowski',47.99,3 ),
 ('Mitologia Nordycka','Neil Gaiman',26.99,4 ),
 ('bóg nie jest wielki','Christopher Hitchens',36.99,5 ),
 ('ZEW CTHULHU: Podręcznki Strażnika Tajemnic','Chaosium Entertainment',219.99,6 ),
 ('WAMPIR:Maskarada','World Of Darkness',209.99,7 ),
 ('AGONIA:Ponura Gra Fabularna','Simon Piecha',109.99,8 ),
 ('Witcher: Tabletop Role Playing Game','R. Talsorian Games',209.99,9 ),
 ('Dungeons&Dragons:Player Handbook','Wizards Of The Coast',179.99,10 ),
 ('Ja, Inkwizytor: Sługa Boży','Jacek Piekara',33.99,11 ),
 ('Narodziny Hordy','Christie Golden',23.99,12 )